name: AI Code Review

on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [opened, synchronize]
  issues:
    types: [opened, edited]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: AI Code Review
        uses: ErRickow/ai-code-review@v1
        with:
          custom_endpoint: ${{ secrets.AI_ENDPOINT }}
          custom_endpoint_param: 'text'
          custom_endpoint_headers: |
            {
              "Authorization": "Bearer ${{ secrets.AI_API_KEY }}"
            }
          review_type: ${{ github.event_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          max_files: 5